package:
  name: cobraxy
  version: "0.1.0"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - cairosvg==2.7.1
    - cobra==0.29.0
    - joblib==1.4.2
    - lxml==5.2.2
    - matplotlib==3.7.3
    - numpy==1.24.4
    - pandas==2.0.3
    - pyvips==2.2.3
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.0
    - svglib==1.5.1

test:
  commands:
    - custom_data_generator --help
    - flux_simulation --help
    - flux_to_map --help
    - marea_cluster --help
    - marea --help
    - ras_generator --help
    - ras_to_bounds --help
    - rps_generator --help

about:
  home: "https://github.com/CompBtBs/COBRAxy.git"
  license: ""
  summary: "A collection of tools for metabolic flux analysis in Galaxy."
  description: "COBRAxy is a set of computational tools designed to perform flux analysis using various methods, integrated into Galaxy for ease of use in bioinformatics workflows."
